### PR TITLE
Add sln file and specific file location support

### LINKED ISSUE #46: Execute at solution level
When trying to execute `dotnet retire` at solution level, i do get the following exception 

> No assets found. Are you running the tool from a folder missing a csproj?

Therefore support for solutions instead of csproj only would be really nice

### PR DESCRIPTION
**Pull request by SiberaIndustries**
Hi,

this PR fixes #46 and adds support for specific file locations on top.

- Add `-p` / `--path` cmd option support
- Add `Path` option property
- Add solution evaluation support

Examples

- `dotnet retire -p <path/to/project/or/sln>`
- `dotnet retire --path <path/to/project/or/sln>`

### CODE REVIEW

**Comment by johnkors** [comment]
Very cool! I could not get it to work, though - maybe I'm missing something. When I tried to add a test sln file and run dotnet retire on it, it gave errors: 

I added this test: https://github.com/RetireNet/dotnet-retire/commit/15d947c9032d10ff3ffc344e448420692dd358e7

And it failed with:https://travis-ci.org/RetireNet/dotnet-retire/builds/605154627#L2448

**Comment by SiberaIndustries** [comment]
> Very cool! I could not get it to work, though - maybe I'm missing something. When I tried to add a test sln file and run dotnet retire on it, it gave errors:
> 
> I added this test: [15d947c](https://github.com/RetireNet/dotnet-retire/commit/15d947c9032d10ff3ffc344e448420692dd358e7)
> 
> And it failed with:https://travis-ci.org/RetireNet/dotnet-retire/builds/605154627#L2448

I failed with a classic 'environment independent file operation' :)

The vulnerable app is referenced in the solution with a backslash (`\`) and this is not a legal directory separator in linux environments. Sadly `Path.GetFullPath` or `Path.Compine` produces `/VulnerableSolution/VulnerableApp\VulnerableApp.csproj` and this is obviously wrong. But I was able to fix it quickly.

**Comment by SiberaIndustries** [comment]
No big deal, but to do so, some architectural changes are required:
- Iterating through lock file moves from `NugetProjectModelAssetsFileParser` into `RetireLogger`
- To get NuGet references by specific projects, the `GetNugetReferences` must accept a parameter (I decided to use `LockFile` type)

What do you think?

**Comment by johnkors** [comment]
Looks very nice! I'll add the Docker test I mentioned on top and merge your commits in a new PR.  Thanks again for contributing!

**Comment by SiberaIndustries** [comment]
Sounds good. Thx. I will move on to the 'Non-zero return' issue and open a separate pr probably this night.

**Comment by johnkors** [comment]
Merged as #57

**Comment by johnkors** [comment]
I could not get the `-p / --path` argument to work, after release. Did you get it working?

```
➜  dotnet-retire git:(master) ✗ dotnet retire -p ./SampleProjects/VulnerableSolution.sln loglevel=debug
dbug: RetireNet.Packages.Tool.Services.DotNet.DotNetExeWrapper[0]
      Not found!
info: RetireNet.Packages.Tool.Services.RetireLogger[0]
      Scan starting
dbug: RetireNet.Packages.Tool.Services.RetireApiClient[0]
      Fetching known vulnerable packages from https://raw.githubusercontent.com/RetireNet/Packages/master/index.json
dbug: RetireNet.Packages.Tool.Services.DotNet.DotNetRunner[0]
      Path to `dotnet` : dotnet
dbug: RetireNet.Packages.Tool.Services.RetireLogger[0]
      `dotnet restore output:`
dbug: RetireNet.Packages.Tool.Services.RetireLogger[0]
      `dotnet restore errors:`
dbug: RetireNet.Packages.Tool.Services.RetireLogger[0]
      `dotnet restore exitcode:`20
fail: RetireNet.Packages.Tool.Services.RetireLogger[0]
      Failed to `dotnet restore`. Is the current dir missing a csproj?
```

**Comment by SiberaIndustries** [comment]
Please try to specify just the path to the solution or csproj instead of the file:

`dotnet retire -p ./SampleProjects/ loglevel=debug`

The `FileService` will automatically check if there is a solution file before it expects a single csproj. Also, think about using dashes, to be safe from wrong interpreted arguments:

`dotnet retire -p ./SampleProjects/ --loglevel debug`

**Comment by johnkors** [comment]
Ah, path to folder. I misread to readme to be path to sln file. Thanks. Maybe we should add support for providing a csproj/sln file in addition to folder, so it "just works".

**Pull request closed without merging**
