### PR TITLE
Return non-zero exit code on failures

### LINKED ISSUE #49: Non-zero return code when vulnerabilities found
Could the tool return a non-zero value when vulnerabilities are found so it can be run as part of a CI pipeline.

Thanks

### PR DESCRIPTION
**Pull request by SiberaIndustries**
Hey,

this PR fixes #49 and always returns a non-zero exit code by default. Optionally there is an `--ignore-failures` opt-out argument option, which can be set to true to always return a zero exit code.

Examples

- Opt In (default): `dotnet retire --ignore-failures false`
- Opt out: `dotnet retire --ignore-failures true`

ToDos

- [x] Return non-zero exit codes by default
- [x] Add opt out option
- [x] Add documentation
- [x] Add tests
- [x] Check and fix possible docker build test errors

### CODE REVIEW

**Comment by johnkors** [comment]
Hi, could you add a test run in the Dockerfiles (Linux/Windows) for non-zero exit codes? I guess we would have to wrap that in a bash+powershell script and capture the exit code (log it).

I would have expected the docker test to fail, since it now returns non-zero exit codes - so the successful run indicates that it's actually returning success..?

**Comment by SiberaIndustries** [comment]
> Hi, could you add a test run in the Dockerfiles (Linux/Windows) for non-zero exit codes? I guess we would have to wrap that in a bash+powershell script and capture the exit code (log it).

Yes I am already working on it. I also think about testing it in a unit / integration test. But for that I would recommend to refactor the test project at all. But this could be a separate PR, because I am thinking about:

- Coverage reports
- Mocking Interfaces with frameworks such as FakeItEasy or Moq
- Replacing NoOpLogger with `NullLogger<T>` provided from Microsoft
- Many unit / integration tests

> I would have expected the docker test to fail, since it now returns non-zero exit codes - so the successful run indicates that it's actually returning success..?

Since it is returning non-zero exit codes, I had to modify the Dockerfiles as well in this commit 9b5de8635f0506865c49f7041db3b56cf4c3551c, to let everything pass for the moment.

**Comment by SiberaIndustries** [comment]
Okay, every task should be completed (fingers crossed). I had to add two scripts (batch for windows / bash for linux) to wrap your commands of the dockerfiles into a separate where I can assert the exit codes. What do you think @johnkors?

As I said, I would recommend adding some unit and integration tests but not as part of this PR. This should be done in a separate PR where the whole test project gets evaluated and refactored.

**Comment by johnkors** [comment]
I think it looks good! Thanks! 

About the other improvements
> Coverage reports

No strong opinions here. 

> Mocking Interfaces with frameworks such as FakeItEasy or Moq

All for using a mocking framework instead of DYI - I usually prefer FakeItEasy for that.

> Replacing NoOpLogger with NullLogger<T> provided from Microsoft

Sure!

> Many unit / integration tests

When it comes to testing, I prefer testing from as far "out" (integration tests / feature tests) as possible, making refactoring of internals easier without also changing alot of unit tests.  It might be that would involve a fair bit of refactoring, but that's ok by me. We should probably open a separate issue to discuss possible refactoring approaches.

I'll merge this, and publish a v3 (I guess the exit code is a breaking change from a client perspective, since the default is not backwards compatible).

**Pull request merged**
